#include <map>

std::map<int, String> student_data{
    {69, "Siddharth Kulkarni"},
    {96 , "Shivraj Ambilwade"},
    {3, "Atharva Shinde"},
    {4, "Yash Dangi"},
    {5, "Swarneet Jagtap"},
    {6, "Saurav Kotkar"},
    {7, "Ujjwal Ahire"},
    {8, "Sahil Gupte"},
    {9, "Sakshi Patil"},
    {10, "Parth Gade"},
    {11, "Mahendra Itkelwar"},
    {12, "Tejas Yadav"},
    {13, "Tanmay Chavan"},
    {14, "Abhishek Mulik"},
    {15, "Soham Karkhanis"},
    {16, "Vedant Raut"},
    {17, "Soham Chiplunkar"},
    {18, "Diya Bajaj"},
    {19, "Gayatri Bhor"},
    {20, "Aditya Jadhav"},
    {21, "Shreyas Malode"},
    {22, "Sai Pawar"},
    {23, "Pranjali Neve"},
    {24, "Pushkar Ubhe"},
    {25, "Joytiraditya Deshmukh"},
    {26, "Jidynesh Jagtap"},
    {27, "Sahil Badambe"},
    {28, "Sushrut Satbhai"},
    {29, "Pradyumna Ponkshe"},
    {30, "Jeet Narkhade"},
    {31, "Siddhi Suryawanshi"},
    {32, "Darshan Joshi"},
    {33, "Anasshah Murshad"},
    {34, "Aditi Dekhane"},
    {35, "Abhishek Pawar"},
    {36, "Parth Solanke"},
    {37, "Shantanu Ekad"}
};